# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
- script: |
    echo ---------------> Update
    echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
    sudo add-apt-repository ppa:openjdk-r/ppa
    sudo apt-get -y update
    sudo apt-get -y install openjdk-8-jdk
    sudo apt-get -y install sbt
    sudo apt-get -y install rpm
  displayName: 'Provisioning enviroment'

- script: |
    sbt compile
    sbt test
  displayName: 'Commit Check'

- script: |
    echo Correr las pruebas de integración
  displayName: 'Integration Tests'

- script: |
    sbt rpm:packageBin
  displayName: 'Generating RPM artifact '

- script: |
    echo $USERWEBSERVER@$IPWEBSERVER
    scp -i ./id_azure.pem /home/vsts/work/1/s/gcs-app/target/rpm/RPMS/noarch/gcs-app-2.8.x-1.noarch.rpm azureuser@157.55.199.18:/home/azureuser
  displayName: 'Deploying'
