# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:

- script: |
    echo $WEBSERVERSSHKEY  > id_azure.pem
    cat id_azure.pem
  displayName: 'Deploying'
