# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
- script: |
    echo ---------------> Update
    sudo add-apt-repository ppa:openjdk-r/ppa
    sudo apt-get -y update
    echo ---------------> Installing Java
    sudo apt-get -y install openjdk-8-jdk
    echo ---------------> Checking java
    javac -version
  displayName: 'Installing dependencies'

- script: |
    sbt compile
    sbt test
  displayName: 'Commit Check'

- script: |
    echo Correr las pruebas de integración
  displayName: 'Integration Tests'
